version: '3'
services:
    ngrok:
        image: ngrok
        build:
            context: ./ngrok
            dockerfile: Dockerfile        
        links:
            - flask
        command: ngrok http nginx:80 --authtoken $AUTHTOKEN --log stdout
        restart: always
    nginx:
        image: mynginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        ports:
            - 80:80
        restart: always
        extra_hosts:
            - "host.docker.internal:172.17.0.1"
    flask:
        build:
            context: ./flask
            dockerfile: Dockerfile
        image: flask
        deploy:
            resources:
                reservations:
                    devices:
                        - capabilities: [gpu]
        ports:
            - 5000:5000
        restart: always
        command: python app.py
        volumes:
            - $PWD/flask:/opt
        healthcheck:
            test: curl -f http://localhost:5000/ping || exit 1
            interval: 30s
            timeout: 10s
            retries: 3